export const GET_CONTRACTS = "GET_CONTRACTS";
export const RECEIVE_CONTRACTS = "RECEIVE_CONTRACTS";
export const REQUEST_CONTRACTS = "REQUEST_CONTRACTS";
export const CONTRACT_REQUEST = "CONTRACT_REQUEST";
export const CONTRACT_SUCCESS = "CONTRACT_SUCCESS";
export const CONTRACT_FAILURE = "CONTRACT_FAILURE";
export const ADD_CONTRACT = "ADD_CONTRACT";
export const LOAD_TABLE = "LOAD_TABLE";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const EDIT_CONTRACT = "EDIT_CONTRACT";
export const FETCH_CONTRACT = "FETCH_CONTRACT";
export const REMOVE_CONTRACT = "REMOVE_CONTRACT";

export const ADD_EVENT = "ADD_EVENT";
export const REMOVE_EVENT = "REMOVE_EVENT";
export const EDIT_EVENT = "EDIT_EVENT";
export const FETCH_EVENT = "FETCH_EVENT";
export const GET_EVENTS = "GET_EVENTS";
export const RECEIVE_EVENTS = "RECEIVE_EVENTS";
export const REQUEST_EVENTS = "REQUEST_EVENTS";
export const EVENT_REQUEST = "EVENT_REQUEST";
export const EVENT_SUCCESS = "EVENT_SUCCESS";
export const EVENT_FAILURE = "EVENT_FAILURE";
export const LOAD_EVENTS_TABLE = "LOAD_EVENTS_TABLE";

export const COMBINE_ACTIONS = "COMBINE_ACTIONS";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const LOAD_NOTIFICATION_TABLE = "LOAD_NOTIFICATION_TABLE";

export const ADD_UPLOAD = "ADD_UPLOAD";
export const REMOVE_UPLOAD = "REMOVE_UPLOAD";
export const EDIT_UPLOAD = "EDIT_UPLOAD";
export const GET_UPLOADS = "GET_UPLOADS";
export const SHOW_UPLOAD = "SHOW_UPLOAD";
export const LOAD_UPLOADS_TABLE = "LOAD_UPLOADS_TABLE";
